# ./docker-compose.yml
version: '3'

services:
  app:
    image: adhocore/lemp:8.0
    # For different app you can use different names. (eg: )
    container_name: some-app
    volumes:
      # app source code
      - ./html:/var/www/html
      # db data persistence
      - db_data:/var/lib/mysql
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - 8080:80
      - 3306:3306
      #- 9000:9000
    environment:
      MYSQL_ROOT_PASSWORD: Kalleanka3!3
      MYSQL_DATABASE: appdb
      MYSQL_USER: usr
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_HOST: "%"
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix
  
volumes:
  db_data: {}