# ./docker-compose.yml
version: '3'

services:
  app:
    image: mylemp:1.0
    # For different app you can use different names. (eg: )
    build: 
      context: lemp
      dockerfile: 8.2.Dockerfile

    container_name: telebok
    volumes:
      # app source code
      - ./html:/var/www/html
      # db data persistence
      - db_data:/var/lib/mysql
      - ./nginx:/etc/nginx/conf.d
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - 8080:80
      - 3306:3306
      #- 9000:9000
    environment:
      MYSQL_ROOT_PASSWORD: Kalleanka3!3
      MYSQL_DATABASE: appdb
      MYSQL_USER: usr
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_HOST: "%"
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: xdebug.client_host=host.docker.internal xdebug.client_port=9003
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix
      # docker-php-ext-enable xdebug
    extra_hosts:
    - "host.docker.internal:host-gateway"  
volumes:
  db_data: {}